### ISSUE TITLE
Theme error

### ISSUE THREAD

**Issue by mARUwTC** [solstice23/hexo-theme-argon#13]
7:57:29 PM: $ npm run build
7:57:29 PM: > hexo-site@0.0.0 build
7:57:29 PM: > hexo generate
7:57:30 PM: INFO  Validating config
7:57:30 PM: INFO  Start processing
7:57:30 PM: INFO  Files loaded in 406 ms
7:57:30 PM: ERROR TypeError: /opt/build/repo/themes/argon/layout/post.ejs:2
7:57:30 PM:     1| <% if (is_post()) { %>
7:57:30 PM:  >> 2| 	<%- partial('_partial/content-article', {post: page}) %>
7:57:30 PM:     3| 	<%- partial('_partial/article-bottom', {post: page}) %>
7:57:30 PM:     4| <% } %>
7:57:30 PM:     5| <% if (is_page()) { %>
7:57:30 PM: /opt/build/repo/themes/argon/layout/_partial/content-article.ejs:20
7:57:30 PM:     18| 		<a class="post-title" href="<%= url_for(post.path) %>"><%= post.title %></a>
7:57:30 PM:     19| 		<div class="post-meta">
7:57:30 PM:  >> 20| 			<%
7:57:30 PM:     21| 				let meta_list = theme.article_meta.split('|');
7:57:30 PM:     22| 				for (let i in meta_list){
7:57:30 PM:     23| 					if (meta_list[i] == 'time'){ %>
7:57:30 PM: Cannot read properties of undefined (reading 'split')
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/_partial/content-article.ejs":46:40)
7:57:30 PM:     at content-article (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at _View._compiledSync (/opt/build/repo/node_modules/hexo/lib/theme/view.js:132:24)
7:57:30 PM:     at _View.renderSync (/opt/build/repo/node_modules/hexo/lib/theme/view.js:59:25)
7:57:30 PM:     at Object.partial (/opt/build/repo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/post.ejs":13:17)
7:57:30 PM:     at post (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at _View._compiled (/opt/build/repo/node_modules/hexo/lib/theme/view.js:136:50)
7:57:30 PM:     at _View.render (/opt/build/repo/node_modules/hexo/lib/theme/view.js:39:17)
7:57:30 PM:     at /opt/build/repo/node_modules/hexo/lib/hexo/index.js:64:21
7:57:30 PM:     at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
7:57:30 PM:     at /opt/build/repo/node_modules/bluebird/js/release/method.js:15:34
7:57:30 PM:     at RouteStream._read (/opt/build/repo/node_modules/hexo/lib/hexo/router.js:47:5)
7:57:30 PM:     at RouteStream.Readable.read (node:internal/streams/readable:487:10)
7:57:30 PM:     at resume_ (node:internal/streams/readable:988:12)
7:57:30 PM:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
7:57:30 PM:   path: '/opt/build/repo/themes/argon/layout/post.ejs'
7:57:30 PM: }
7:57:30 PM: ERROR TypeError: /opt/build/repo/themes/argon/layout/index.ejs:2
7:57:30 PM:     1| <% page.posts.each(function(post){ %>
7:57:30 PM:  >> 2| 	<%- partial('_partial/content-preview', {post: post}) %>
7:57:30 PM:     3| <% }) %>
7:57:30 PM:     4| <%- partial('_partial/pagination', {page: page}) %>
7:57:30 PM: /opt/build/repo/themes/argon/layout/_partial/content-preview.ejs:12
7:57:30 PM:     10| 		<a class="post-title" href="<%= url_for(post.path) %>"><%= post.title %></a>
7:57:30 PM:     11| 		<div class="post-meta">
7:57:31 PM: Creating deploy upload records
7:57:30 PM:  >> 12| 			<%
7:57:30 PM:     13| 				let meta_list = theme.article_meta.split('|');
7:57:30 PM:     14| 				for (let i in meta_list){
7:57:30 PM:     15| 					if (meta_list[i] == 'time'){ %>
7:57:30 PM: Cannot read properties of undefined (reading 'split')
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/_partial/content-preview.ejs":37:40)
7:57:30 PM:     at content-preview (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at _View._compiledSync (/opt/build/repo/node_modules/hexo/lib/theme/view.js:132:24)
7:57:30 PM:     at _View.renderSync (/opt/build/repo/node_modules/hexo/lib/theme/view.js:59:25)
7:57:30 PM:     at Object.partial (/opt/build/repo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/index.ejs":13:17)
7:57:30 PM:     at _Query.forEach (/opt/build/repo/node_modules/warehouse/lib/query.js:36:7)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/index.ejs":10:19)
7:57:30 PM:     at index (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at _View._compiled (/opt/build/repo/node_modules/hexo/lib/theme/view.js:136:50)
7:57:30 PM:     at _View.render (/opt/build/repo/node_modules/hexo/lib/theme/view.js:39:17)
7:57:30 PM:     at /opt/build/repo/node_modules/hexo/lib/hexo/index.js:64:21
7:57:30 PM:     at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
7:57:30 PM:     at /opt/build/repo/node_modules/bluebird/js/release/method.js:15:34
7:57:30 PM:     at RouteStream._read (/opt/build/repo/node_modules/hexo/lib/hexo/router.js:47:5)
7:57:30 PM:     at RouteStream.Readable.read (node:internal/streams/readable:487:10) {
7:57:30 PM:   path: '/opt/build/repo/themes/argon/layout/index.ejs'
7:57:30 PM: }
7:57:30 PM: ERROR {
7:57:30 PM:   err: TypeError: /opt/build/repo/themes/argon/layout/layout.ejs:1
7:57:30 PM:    >> 1| <%- include('header.ejs') %>
7:57:30 PM:       2|
7:57:30 PM:       3| <div class="page-information-card-container">
7:57:30 PM:       4| 	<% if (is_tag() || is_category() || (is_archive() && page.year != undefined)) { %>
7:57:30 PM:   /opt/build/repo/themes/argon/layout/header.ejs:43
7:57:30 PM:       41|
7:57:30 PM:       42| 	<meta name="theme-color" content="<%= theme.theme_color %>">
7:57:30 PM:    >> 43| 	<meta name="theme-color-rgb" content="<%= hex2str(theme.theme_color) %>">
7:57:30 PM:       44| 	<meta name="theme-color-origin" content="<%= theme.theme_color %>">
7:57:30 PM:       45| 	<meta name="argon-enable-custom-theme-color" content="<%= theme.show_customize_theme_color_picker %>">
7:57:30 PM:       46| 	<meta name="theme-card-radius" content="<%= theme.card_radius %>">
7:57:30 PM:   Cannot read properties of undefined (reading 'toUpperCase')
7:57:30 PM:       at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:154:12)
7:57:30 PM:       at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:178:27)
7:57:30 PM:       at eval ("/opt/build/repo/themes/argon/layout/header.ejs":68:26)
7:57:30 PM:       at header (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:       at include (/opt/build/repo/node_modules/ejs/lib/ejs.js:690:39)
7:57:30 PM:       at eval ("/opt/build/repo/themes/argon/layout/layout.ejs":10:17)
7:57:30 PM:       at layout (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:       at _View._compiled (/opt/build/repo/node_modules/hexo/lib/theme/view.js:136:50)
7:57:30 PM:       at _View.render (/opt/build/repo/node_modules/hexo/lib/theme/view.js:39:17)
7:57:30 PM:       at /opt/build/repo/node_modules/hexo/lib/theme/view.js:51:25
7:57:30 PM:       at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
7:57:30 PM:       at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:547:31)
7:57:30 PM:       at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:604:18)
7:57:30 PM:       at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:649:10)
7:57:30 PM:       at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:729:18)
7:57:30 PM:       at _drainQueueStep (/opt/build/repo/node_modules/bluebird/js/release/async.js:93:12) {
7:57:30 PM:     path: '/opt/build/repo/themes/argon/layout/layout.ejs'
7:57:30 PM:   }
7:57:30 PM: } Render HTML failed: archives/index.html
7:57:30 PM: ERROR {
7:57:30 PM:   err: TypeError: /opt/build/repo/themes/argon/layout/layout.ejs:1
7:57:30 PM:    >> 1| <%- include('header.ejs') %>
7:57:30 PM:       2|
7:57:30 PM:       3| <div class="page-information-card-container">
7:57:30 PM:       4| 	<% if (is_tag() || is_category() || (is_archive() && page.year != undefined)) { %>
7:57:30 PM:   /opt/build/repo/themes/argon/layout/header.ejs:43
7:57:30 PM:       41|
7:57:31 PM: Starting post processing
7:57:30 PM:       42| 	<meta name="theme-color" content="<%= theme.theme_color %>">
7:57:30 PM:    >> 43| 	<meta name="theme-color-rgb" content="<%= hex2str(theme.theme_color) %>">
7:57:30 PM:       44| 	<meta name="theme-color-origin" content="<%= theme.theme_color %>">
7:57:30 PM:       45| 	<meta name="argon-enable-custom-theme-color" content="<%= theme.show_customize_theme_color_picker %>">
7:57:30 PM:       46| 	<meta name="theme-card-radius" content="<%= theme.card_radius %>">
7:57:30 PM:   Cannot read properties of undefined (reading 'toUpperCase')
7:57:31 PM: Post processing - HTML
7:57:30 PM:       at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:154:12)
7:57:30 PM:       at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:178:27)
7:57:30 PM:       at eval ("/opt/build/repo/themes/argon/layout/header.ejs":68:26)
7:57:30 PM:       at header (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:       at include (/opt/build/repo/node_modules/ejs/lib/ejs.js:690:39)
7:57:30 PM:       at eval ("/opt/build/repo/themes/argon/layout/layout.ejs":10:17)
7:57:30 PM:       at layout (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:       at _View._compiled (/opt/build/repo/node_modules/hexo/lib/theme/view.js:136:50)
7:57:30 PM:       at _View.render (/opt/build/repo/node_modules/hexo/lib/theme/view.js:39:17)
7:57:30 PM:       at /opt/build/repo/node_modules/hexo/lib/theme/view.js:51:25
7:57:30 PM:       at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
7:57:30 PM:       at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:547:31)
7:57:30 PM:       at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:604:18)
7:57:30 PM:       at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:649:10)
7:57:30 PM:       at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:729:18)
7:57:30 PM:       at _drainQueueStep (/opt/build/repo/node_modules/bluebird/js/release/async.js:93:12) {
7:57:31 PM: Post processing - header rules
7:57:30 PM:     path: '/opt/build/repo/themes/argon/layout/layout.ejs'
7:57:30 PM:   }
7:57:30 PM: } Render HTML failed: archives/2022/index.html
7:57:30 PM: ERROR {
7:57:30 PM:   err: TypeError: /opt/build/repo/themes/argon/layout/layout.ejs:1
7:57:30 PM:    >> 1| <%- include('header.ejs') %>
7:57:30 PM:       2|
7:57:31 PM: Post processing - redirect rules
7:57:30 PM:       3| <div class="page-information-card-container">
7:57:30 PM:       4| 	<% if (is_tag() || is_category() || (is_archive() && page.year != undefined)) { %>
7:57:30 PM:   /opt/build/repo/themes/argon/layout/header.ejs:43
7:57:30 PM:       41|
7:57:30 PM:       42| 	<meta name="theme-color" content="<%= theme.theme_color %>">
7:57:30 PM:    >> 43| 	<meta name="theme-color-rgb" content="<%= hex2str(theme.theme_color) %>">
7:57:30 PM:       44| 	<meta name="theme-color-origin" content="<%= theme.theme_color %>">
7:57:31 PM: Post processing done
7:57:30 PM:       45| 	<meta name="argon-enable-custom-theme-color" content="<%= theme.show_customize_theme_color_picker %>">
7:57:30 PM:       46| 	<meta name="theme-card-radius" content="<%= theme.card_radius %>">
7:57:30 PM:   Cannot read properties of undefined (reading 'toUpperCase')
7:57:30 PM:       at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:154:12)
7:57:30 PM:       at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:178:27)
7:57:30 PM:       at eval ("/opt/build/repo/themes/argon/layout/header.ejs":68:26)
7:57:30 PM:       at header (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:       at include (/opt/build/repo/node_modules/ejs/lib/ejs.js:690:39)
7:57:30 PM:       at eval ("/opt/build/repo/themes/argon/layout/layout.ejs":10:17)
7:57:30 PM:       at layout (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:       at _View._compiled (/opt/build/repo/node_modules/hexo/lib/theme/view.js:136:50)
7:57:30 PM:       at _View.render (/opt/build/repo/node_modules/hexo/lib/theme/view.js:39:17)
7:57:30 PM:       at /opt/build/repo/node_modules/hexo/lib/theme/view.js:51:25
7:57:30 PM:       at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
7:57:30 PM:       at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:547:31)
7:57:30 PM:       at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:604:18)
7:57:30 PM:       at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:649:10)
7:57:30 PM:       at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:729:18)
7:57:30 PM:       at _drainQueueStep (/opt/build/repo/node_modules/bluebird/js/release/async.js:93:12) {
7:57:30 PM:     path: '/opt/build/repo/themes/argon/layout/layout.ejs'
7:57:30 PM:   }
7:57:30 PM: } Render HTML failed: archives/2022/01/index.html
7:57:30 PM: ERROR TypeError: /opt/build/repo/themes/argon/layout/layout.ejs:1
7:57:30 PM:  >> 1| <%- include('header.ejs') %>
7:57:30 PM:     2|
7:57:30 PM:     3| <div class="page-information-card-container">
7:57:30 PM:     4| 	<% if (is_tag() || is_category() || (is_archive() && page.year != undefined)) { %>
7:57:30 PM: /opt/build/repo/themes/argon/layout/header.ejs:43
7:57:30 PM:     41|
7:57:30 PM:     42| 	<meta name="theme-color" content="<%= theme.theme_color %>">
7:57:30 PM:  >> 43| 	<meta name="theme-color-rgb" content="<%= hex2str(theme.theme_color) %>">
7:57:30 PM:     44| 	<meta name="theme-color-origin" content="<%= theme.theme_color %>">
7:57:30 PM:     45| 	<meta name="argon-enable-custom-theme-color" content="<%= theme.show_customize_theme_color_picker %>">
7:57:30 PM:     46| 	<meta name="theme-card-radius" content="<%= theme.card_radius %>">
7:57:30 PM: Cannot read properties of undefined (reading 'toUpperCase')
7:57:30 PM:     at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:154:12)
7:57:30 PM:     at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:178:27)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/header.ejs":68:26)
7:57:30 PM:     at header (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at include (/opt/build/repo/node_modules/ejs/lib/ejs.js:690:39)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/layout.ejs":10:17)
7:57:30 PM:     at layout (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at _View._compiled (/opt/build/repo/node_modules/hexo/lib/theme/view.js:136:50)
7:57:30 PM:     at _View.render (/opt/build/repo/node_modules/hexo/lib/theme/view.js:39:17)
7:57:30 PM:     at /opt/build/repo/node_modules/hexo/lib/theme/view.js:51:25
7:57:30 PM:     at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
7:57:30 PM:     at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:547:31)
7:57:30 PM:     at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:604:18)
7:57:30 PM:     at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:649:10)
7:57:30 PM:     at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:729:18)
7:57:30 PM:     at _drainQueueStep (/opt/build/repo/node_modules/bluebird/js/release/async.js:93:12) {
7:57:30 PM:   path: '/opt/build/repo/themes/argon/layout/layout.ejs'
7:57:30 PM: }
7:57:30 PM: ERROR TypeError: /opt/build/repo/themes/argon/layout/layout.ejs:1
7:57:30 PM:  >> 1| <%- include('header.ejs') %>
7:57:30 PM:     2|
7:57:30 PM:     3| <div class="page-information-card-container">
7:57:30 PM:     4| 	<% if (is_tag() || is_category() || (is_archive() && page.year != undefined)) { %>
7:57:30 PM: /opt/build/repo/themes/argon/layout/header.ejs:43
7:57:30 PM:     41|
7:57:30 PM:     42| 	<meta name="theme-color" content="<%= theme.theme_color %>">
7:57:30 PM:  >> 43| 	<meta name="theme-color-rgb" content="<%= hex2str(theme.theme_color) %>">
7:57:30 PM:     44| 	<meta name="theme-color-origin" content="<%= theme.theme_color %>">
7:57:30 PM:     45| 	<meta name="argon-enable-custom-theme-color" content="<%= theme.show_customize_theme_color_picker %>">
7:57:30 PM:     46| 	<meta name="theme-card-radius" content="<%= theme.card_radius %>">
7:57:30 PM: Cannot read properties of undefined (reading 'toUpperCase')
7:57:30 PM:     at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:154:12)
7:57:30 PM:     at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:178:27)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/header.ejs":68:26)
7:57:30 PM:     at header (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at include (/opt/build/repo/node_modules/ejs/lib/ejs.js:690:39)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/layout.ejs":10:17)
7:57:30 PM:     at layout (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at _View._compiled (/opt/build/repo/node_modules/hexo/lib/theme/view.js:136:50)
7:57:30 PM:     at _View.render (/opt/build/repo/node_modules/hexo/lib/theme/view.js:39:17)
7:57:30 PM:     at /opt/build/repo/node_modules/hexo/lib/theme/view.js:51:25
7:57:30 PM:     at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
7:57:30 PM:     at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:547:31)
7:57:30 PM:     at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:604:18)
7:57:30 PM:     at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:649:10)
7:57:30 PM:     at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:729:18)
7:57:30 PM:     at _drainQueueStep (/opt/build/repo/node_modules/bluebird/js/release/async.js:93:12) {
7:57:30 PM:   path: '/opt/build/repo/themes/argon/layout/layout.ejs'
7:57:30 PM: }
7:57:30 PM: ERROR TypeError: /opt/build/repo/themes/argon/layout/layout.ejs:1
7:57:30 PM:  >> 1| <%- include('header.ejs') %>
7:57:30 PM:     2|
7:57:30 PM:     3| <div class="page-information-card-container">
7:57:30 PM:     4| 	<% if (is_tag() || is_category() || (is_archive() && page.year != undefined)) { %>
7:57:30 PM: /opt/build/repo/themes/argon/layout/header.ejs:43
7:57:30 PM:     41|
7:57:30 PM:     42| 	<meta name="theme-color" content="<%= theme.theme_color %>">
7:57:30 PM:  >> 43| 	<meta name="theme-color-rgb" content="<%= hex2str(theme.theme_color) %>">
7:57:30 PM:     44| 	<meta name="theme-color-origin" content="<%= theme.theme_color %>">
7:57:30 PM:     45| 	<meta name="argon-enable-custom-theme-color" content="<%= theme.show_customize_theme_color_picker %>">
7:57:30 PM:     46| 	<meta name="theme-card-radius" content="<%= theme.card_radius %>">
7:57:30 PM: Cannot read properties of undefined (reading 'toUpperCase')
7:57:30 PM:     at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:154:12)
7:57:30 PM:     at Object.<anonymous> (/opt/build/repo/themes/argon/scripts/functions.js:178:27)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/header.ejs":68:26)
7:57:30 PM:     at header (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at include (/opt/build/repo/node_modules/ejs/lib/ejs.js:690:39)
7:57:30 PM:     at eval ("/opt/build/repo/themes/argon/layout/layout.ejs":10:17)
7:57:30 PM:     at layout (/opt/build/repo/node_modules/ejs/lib/ejs.js:692:17)
7:57:30 PM:     at _View._compiled (/opt/build/repo/node_modules/hexo/lib/theme/view.js:136:50)
7:57:30 PM:     at _View.render (/opt/build/repo/node_modules/hexo/lib/theme/view.js:39:17)
7:57:30 PM:     at /opt/build/repo/node_modules/hexo/lib/theme/view.js:51:25
7:57:30 PM:     at tryCatcher (/opt/build/repo/node_modules/bluebird/js/release/util.js:16:23)
7:57:30 PM:     at Promise._settlePromiseFromHandler (/opt/build/repo/node_modules/bluebird/js/release/promise.js:547:31)
7:57:30 PM:     at Promise._settlePromise (/opt/build/repo/node_modules/bluebird/js/release/promise.js:604:18)
7:57:30 PM:     at Promise._settlePromise0 (/opt/build/repo/node_modules/bluebird/js/release/promise.js:649:10)
7:57:30 PM:     at Promise._settlePromises (/opt/build/repo/node_modules/bluebird/js/release/promise.js:729:18)
7:57:30 PM:     at _drainQueueStep (/opt/build/repo/node_modules/bluebird/js/release/async.js:93:12) {
7:57:30 PM:   path: '/opt/build/repo/themes/argon/layout/layout.ejs'
7:57:30 PM: }

**Comment by Lparksi** [comment]
hexo现在已经不再内置 `ejs ` 渲染器了

在hexp目录下运行以下命令安装以解决你的问题
```
npm install hexo-renderer-ejs
```
