### ISSUE TITLE
A Bug of wordcount

### ISSUE THREAD

**Issue by wxkj123** [solstice23/hexo-theme-argon#14]
这个我clone完主题之后没动过什么东西，结果字数给我少了好几倍
我这里有个文档明明要有3k字的给我数成了600。。。
据wordcount插件作者称你把插件魔改了（
请求修复

**Comment by solstice23** [comment]
@wxkj123 当时不知道为什么多了一个反斜杠（
https://github.com/solstice23/hexo-theme-argon/blob/ee427a05caa2d00a6f8407b7f5fec66424fd5dda/scripts/functions.js#L182-L219
和插件做了 diff，只有正则的地方不同

**Comment by wxkj123** [comment]
多谢 @solstice23
