### ISSUE TITLE
可在選單上添加圖標的插件皆不起作用

### ISSUE THREAD

**Issue by whitebear13579** [solstice23/hexo-theme-argon#24]
如題，可在選單上添加圖標的插件都不起做作用，有開啟疑難排解模式，發現在主題不是Argon時插件都正常，但當主題設置為Argon時就會無法顯示。
可是看到作者您的Blog上導覽列的選單可以正常顯示，想請問怎麼修復，或是您是使用哪一款插件呢?
目前測試過的插件:
WP Menu Icons [完全不可用]
Menu Icons by ThemeIsle [完全不可用]
![is1](https://user-images.githubusercontent.com/68762923/179785434-4091ddd5-32e3-4e72-be0e-8671095fd253.png)

在選單頁面已經設定icon:
![image](https://user-images.githubusercontent.com/68762923/179785691-d4591f39-ec30-41eb-b312-3710333d68f4.png)

無法正常顯示:
![image](https://user-images.githubusercontent.com/68762923/179785815-b456b1d1-5288-46ee-8fa8-038610dd3475.png)

**Comment by solstice23** [comment]
此 Repo 为 hexo 版本，请在 wordpress repo 下开 issue

**Comment by solstice23** [comment]
https://argon-docs.solstice23.top/#/icon
