### ISSUE TITLE
代码区域渲染错误

### ISSUE THREAD

**Issue by Lostiz** [solstice23/hexo-theme-argon#25]
如图，只渲染出框
![a](https://user-images.githubusercontent.com/99953892/180619223-5e3a0295-8174-4f7d-948f-e0697812f657.jpg)

以下插件
![b](https://user-images.githubusercontent.com/99953892/180619265-74c30f18-dceb-4dc1-991a-950be2d5c9a7.jpg)
开启highlight无效
![c](https://user-images.githubusercontent.com/99953892/180619341-1626ffa3-7ee7-4ef6-961e-afafedccc500.jpg)
代码超出渲染也错误
![d](https://user-images.githubusercontent.com/99953892/180619418-d62c37b6-a636-432a-8c32-3c2f99f15650.jpg)

Node.js版本为v18.6.0
系统win10，11都试过

**Comment by wxkj123** [comment]
我遇到了同样的问题，请问你是怎么解决的呢

**Comment by ch-tj-hx-song** [comment]
@Lostiz 请问你是怎么解决的呢，我也有这个问题

**Comment by ch-tj-hx-song** [comment]
@wxkj123 把**站点根目录**下的 `config.yml` 中的 `highlight` 关掉就可以了，主题的高亮和hexo自带的高亮冲突了
