### ISSUE TITLE
代码块渲染错误

### ISSUE THREAD

**Issue by picpo** [solstice23/hexo-theme-argon#28]
![image](https://user-images.githubusercontent.com/33993624/209559465-f4aa7ef4-e79a-470b-bf16-7f06cb151cf2.png)
如图，代码中若是有过长的语句会导致渲染错误
还有请问可以和wordpress版本一样切换代码块风格吗

**Comment by cloudw233** [comment]
hexo自带代码高亮与主题冲突，关闭掉hexo的_config.yml内的代码高亮，使用主题的即可
