### ISSUE TITLE
代码框样式

### ISSUE THREAD

**Issue by stmoonar** [solstice23/hexo-theme-argon#31]
代码框和wordpress版的好像不太一样，是本来就是这样的还是我的问题
<img width="321" alt="image" src="https://github.com/solstice23/hexo-theme-argon/assets/128700661/aed6e2d4-a259-4caf-bc97-f5aeb1668f44">
如果本来就是这样怎么改成和wordpress版的一样的代码框呢

**Comment by XianyanXie** [comment]
解决了，应该是主题配置文件和hexo配置文件冲突

**Comment by csh1311** [comment]
如何解决的吗

**Comment by XianyanXie** [comment]
> 如何解决的吗

把hexo的_config.yml配置文件里面的highlight enable改成false就好了
<img width="156" alt="image" src="https://github.com/solstice23/hexo-theme-argon/assets/128700661/1c6c7550-ea35-4727-ba1c-60e29168a6c9">

**Comment by jkjoy** [comment]
都关了也没用
