### ISSUE TITLE
标题打字效果速度异常

### ISSUE THREAD

**Issue by Yuhongyi2011** [solstice23/hexo-theme-argon#36]
我在修改_config.yml时打开了打字效果的选项，并设置了间隔，但在实际使用时打字间隔非常短，几乎看不出来
代码如下
``enable_banner_title_typing_effect: true # 是否启用 Banner 打字效果
theme.banner_typing_effect_interval: 5 # Banner 打字间隔时长，单位 ms/字
banner_subtitle: 'Just Go For It' # Banner 子标题，留空则不显示``
如果是bug希望尽快修复

**Comment by solstice23** [comment]
`theme.banner_typing_effect_interval: 5`
`单位 ms/字`

**Comment by Yuhongyi2011** [comment]
还是不行啊

**Comment by Yuhongyi2011** [comment]
谢谢，我去看看
