### ISSUE TITLE
如何使背景图有落雪特效

### ISSUE THREAD

**Issue by lxy6515** [solstice23/hexo-theme-argon#7]
看到例站有很羡慕     还有是关于搜索   我的搜索是点击弹出内置搜索框   如何达到https://solstice23.top/的搜索框

**Comment by solstice23** [comment]
1. 相同 Issue https://github.com/solstice23/argon-theme/issues/155
2. 新搜索框效果是 Wordpress 某个版本以后加的，Hexo 版本还是加上这个特性之前移植的，没(tou)跟(lan)上(le)，以后应该会跟进，随缘更新，~~同时欢迎 Pull Request 帮助移植~~。
