### ISSUE TITLE
无法使用短代码

### ISSUE THREAD

**Issue by WindLeaf233** [solstice23/hexo-theme-argon#9]
我在文章中添加了几个短代码:
[alert]提示[/alert]
[progressbar progress="10"]进度条[/progressbar]
[collapse title="折叠区块"]折叠[/collapse]
[github author="solstice23" project="argon-theme"][/github]

我的 Markdown 文件长这样:
![1](https://user-images.githubusercontent.com/58383985/121813765-1f7c3700-cca0-11eb-8b98-c4eb80067dc2.jpg)

但是, hexo server 和 hexo generate 出来的都是这样的:
![2](https://user-images.githubusercontent.com/58383985/121813888-b9dc7a80-cca0-11eb-90bb-3326f164815a.jpg)

这是 hexo 版 argon 尚未添加该功能的原因吗？

**Comment by solstice23** [comment]
是

**Comment by WindLeaf233** [comment]
> 是

好吧, 希望可以早点出这个功能

**Comment by solstice23** [comment]
可以先暂时添加 HTML 代码代替下（

**Comment by WindLeaf233** [comment]
> 可以先暂时添加 HTML 代码代替下（

好的
